"""Add posts table

Revision ID: ac159cd11cdd
Revises: 047a1332f3fd
Create Date: 2025-07-02 03:38:11.459620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac159cd11cdd'
down_revision: Union[str, Sequence[str], None] = '047a1332f3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_wallets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('seed_phrase', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('key_words', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('change_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_wallets')
    # ### end Alembic commands ###
